[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "lxml>=6.0.0",
    "pandas>=2.3.1",
    "python-magic>=0.4.27",
    "reportlab>=4.4.3",
    "streamlit>=1.47.0",
]
