[azure]
# Azure OpenAI Configuration (placeholder values)
AZURE_OPENAI_ENDPOINT = ""
AZURE_OPENAI_KEY = ""
AZURE_OPENAI_API_VERSION = "2024-02-15-preview"
AZURE_OPENAI_DEPLOYMENT = "gpt-4-32k"

# Azure Form Recognizer Configuration
AZURE_FORM_RECOGNIZER_ENDPOINT = ""
AZURE_FORM_RECOGNIZER_KEY = ""

# Azure AI Agent Configuration
AZURE_AI_AGENT_ENDPOINT = ""
AZURE_AI_AGENT_KEY = ""
AZURE_AI_AGENT_ID = ""

# Azure Text Analytics Configuration
AZURE_TEXT_ANALYTICS_ENDPOINT = ""
AZURE_TEXT_ANALYTICS_KEY = ""

# Azure Resource Configuration
AZURE_SUBSCRIPTION_ID = ""
AZURE_RESOURCE_GROUP = "e2b-converter-rg"
AZURE_TENANT_ID = ""